export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const PRODUCT_ADDED_TO_CART = 'PRODUCT_ADDED_TO_CART';
export const ITEM_REMOVED_FROM_CART = 'ITEM_REMOVED_FROM_CART';
export const PRODUCT_REMOVED_FROM_CART = 'PRODUCT_REMOVED_FROM_CART';
export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
